# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: noo-loo-poh exception
email: wataash0607@gmail.com
# description: >
#   Awesome site description here
# logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nlpex.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'wataash'
bio: >
  TODO
author_image: "/assets/images/author.jpg"
twitter_username: wata_ash
github_username:  wataash

# Google Analytics
analytics_id: "UA-69723762-3"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
